version: '3'

services:

  synapse:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    image: docker.io/matrixdotorg/synapse:latest
    # Since synapse does not retry to connect to the database, restart upon
    # failure
    restart: unless-stopped
    volumes:
      # Everything is stored in the system drive for the moment, if it needs 
      # more space it'll be placed on an external drive
      - /home/anya/Services/synapse-2024/files:/data